### ISSUE TITLE
Import the French localization work

### ISSUE THREAD

**Issue by garronej** [italia/publiccode-editor#229]
Dear Italians counterparts,  
I am working [@etalab](https://www.etalab.gouv.fr) with @bzg. 
We are considering hosting our own instance of publiccode-editor.  
We are going to test this out first but if we do choose to put this in production there are two things that we would have to tackle:  

1) Translate the app in French. ~I saw [everything was tokenized already](https://github.com/italia/publiccode-editor/blob/c419af5b96b7d1d81ef48af177f91d1a6cfbb5dd/src/app/contents/fields/generic.js) so it shouldn't be a big deal~.  
2) The app relies on [environment variables](https://github.com/italia/publiccode-editor/blob/master/src/app/contents/constants.js) that are injected into the app at build time so we are forced to build our own 
version if we want to use our own values. I created [a module](https://github.com/garronej/cra-envs) to tackle this exact problem we were facing with [Onyxia](https://github.com/InseeFrLab/onyxia).  

I guess my question is  
Are you open contributions and are you interested in the features I am offering to implement?  

Best regards,

**Comment by bfabio** [comment]
Hi @garronej, that's great news!

The editor was undergoing a big refactoring and we are picking up where we left off. Since it includes a rework of the i18n is handled, I suggest you to take a look [at that branch](https://github.com/sebbalex/publiccode-editor/tree/refactor) in order to possibly base your work on it.

**Comment by bfabio** [comment]
That's too bad, but not the end of the world. I'll keep this issue opened as a reminder of merging your work into the refactored editor once we merge it into master.

The advice of using the refactor branch as reference still stands because it's a significant change from master.

**Comment by bzg** [comment]
> The advice of using the refactor branch as reference still stands because it's a significant change from master.

Fully agreed: let's follow _your_ pace and direction.  @garronej: your work is not lost, it is part of exploring the current solution and what you learned/contributed will be useful later on for sure.

**Comment by garronej** [comment]
No problem that's no big deal!  
We could integrate our translation to your branch once it's merged.  
Just ping me when it's done and I will do it!

**Comment by giosce** [comment]
I'm working on something similar, I want to have an American version and more precisely a version for Code for America and other large civic tech American organizations.
Luckily I don't need translation has most description is already in English.
One main customization is to populate some dropdowns by calling our Taxonomy API, so far it seems I can make it driven by environment variables.
I'll also make many fields non mandatory and add some fields. While I see the mechanism to add country (or organization) fields fairly modular, from what I saw so far, making fields mandatory or not seems hardcoded in generic.js. I'm trying to bring as much configuration as possible outside js files (typically in .env).
Writing these things here because they seem within the same scope of this issue but I'd love if there is a more interactive place were we can "discuss" better this type of proposed changes, like Slack or similar.

**Comment by bzg** [comment]
Thanks!
