### ISSUE TITLE
Newlines are not kept in longDescription

### ISSUE THREAD

**Issue by alranel** [italia/publiccode-editor#51]
As of now, the `>-` syntax is used for multiline fields. However this will not preserve newlines correctly. For instance:

```yaml
    longDescription: |
      Agave è composto dai seguenti blocchi logici:

      * Un'**area amministrativa** (CMS)
      * Un **sito web statico** (Jekyll) contenente un **template** Jekyll
```

will be parsed as:

```yaml
    longDescription: |-
      Agave è composto dai seguenti blocchi logici:
      * Un'**area amministrativa** (CMS) * Un **sito web statico** (Jekyll) contenente un **template** Jekyll
```

We need to use `|-` instead of `>-`, as explained here: https://yaml-multiline.info

I think this change should only apply to longDescription, where we might expect text with newlines.

**Comment by sebbalex** [comment]
as for now the editor produce the longDescription field using `>` operator

**Comment by sebbalex** [comment]
Library used for yaml conversion manages long string field in a proper logic way. Since this [PR#181](https://github.com/nodeca/js-yaml/pull/181) related to issue [#66](https://github.com/nodeca/js-yaml/issues/66#issuecomment-77416187) adds this behaviour.
Actually there is no parameter to set folded/literal scalar block.

To achieve our goal we have two ways in front of us:
- go back to html format and use `<br />` tag to manage newlines and translate back to markdown in parser.
- set the lineWidth parameter ([doc](https://github.com/nodeca/js-yaml#safedump-object---options-)) to force the `|` operator but we will have very long line in yaml, so bad for readability.

**Comment by alranel** [comment]
Further testing shows that publiccode-editor generates valid YAML. It tries to be smart to sometimes it uses `>` and other times it uses `|`. When `>` is used, additional newlines are inserted in the document, for example:

```
foo: >
  * foo
  
  * bar
```

This seems to be correctly parsed as `* foo\n*bar` because `>` collapses multiple newlines, so the round-trip is correct. However, the YAML file becomes not user-friendly and easy to edit because a human would never understand why double newlines should be inserted in a Markdown list.
We probably need a way for forcing `|` so that the YAML file contains literal strings and stays human-editable.

**Comment by bfabio** [comment]
This depends on https://github.com/nodeca/js-yaml/pull/515 being merged, unless we want to workaround it.
